### ISSUE TITLE
Error: Cannot find module 'try-thread-sleep'

### ISSUE THREAD

**Issue by overclokk** [Mte90/generator-wp-plugin-boilerplate-powered#5]
I tried to use yeoman generator but I got this error

```
F:\xampp\htdocs\template\wp-content\plugins>yo wp-plugin-boilerplate-powered

Error: Cannot find module 'try-thread-sleep'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\fisso\AppData\Roaming\npm\node_modules\gener
ator-wp-plugin-boilerplate-powered\node_modules\spawn-sync\lib\spawn-sync.js:7:1
3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

try-thread-sleep module is installed and spawn-sync too
I'm on Windows 7, npm 1.4.3, yeoman 1.4.7

**Comment by Mte90** [comment]
I've searched and do it some test.
I've no idea because this module is a dependence of spawn-sync.
Spawn-sync is not installed globally so maybe try-thread-sleep?

**Comment by overclokk** [comment]
Great, I had to install `try-thread-sleep` globally, not locally :-)

Thanks :-)
